<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Insert title here</title>
<link rel="stylesheet" type="text/css"
	href="../lib/ext-4.2.1.883/resources/css/ext-all.css">
<script type="text/javascript"
	src="../lib/ext-4.2.1.883/ext-all-debug-w-comments.js">
</script>
<!-- 
Ext Js Component Document
http://docs.sencha.com/extjs/4.2.1/#!/api/Ext
 -->
</head>
<body>
</body>
<script type="text/javascript">
Ext.onReady(function () {
	
	var cycleButton = Ext.create('Ext.button.Cycle', {
	    showText: true,
	    prependText: 'View as ',
	    renderTo: Ext.getBody(),
	    menu: {
	        id: 'view-type-menu',
	        items: [{
	            text: 'text only',
	            iconCls: 'view-text',
	            checked: true
	        },{
	            text: 'HTML',
	            iconCls: 'view-html'
	        }]
	    },
	    changeHandler: function(cycleBtn, activeItem) {
	        Ext.Msg.alert('Change View', activeItem.text);
	    }
	});
	
	Ext.create('Ext.container.Container', {
	    layout: {
	        type: 'hbox'
	    },
	    width: 400,
	    height:50,
	    renderTo: Ext.getBody(),
	    layout:"auto",
	    border: 1,
	    style: {borderColor:'#000000', borderStyle:'solid', borderWidth:'1px'},
	    defaults: [{
	        labelWidth: 80,
	        // implicitly create Container by specifying xtype
	        xtype: 'datefield',
	        flex: 1,
	        style: {
	            padding: '10px'
	        }
	    }]
	    ,
	    items: [{
	        xtype: 'datefield',
	        name: 'startDate',
	        fieldLabel: 'Start date'
	    },{
	        xtype: 'datefield',
	        name: 'endDate',
	        fieldLabel: 'End date'
	    },
	    {
	    	xtype: 'button',
	    	name: 'btn',
	    	text: 'Button',
	    	 handler: function() {
	    	        alert('You clicked the button!');
	    	    }
	    },
	    cycleButton
	    ]
	});
	
});
</script>
</html><!-- 
xtype 사용 가능 component
 
 actioncolumn : Alias for Ext.grid.column.Action. ...
 
 booleancolumn : Alias for Ext.grid.column.Boolean. ...
 
 boundlist : Alias for Ext.view.BoundList. ...
 
 box : Alias for Ext.Component. ...
 
 button : Alias for Ext.button.Button. ...
 
 buttongroup : Alias for Ext.container.ButtonGroup. ...
 
 chart : Alias for Ext.chart.Chart. ...
 
 checkbox : Alias for Ext.form.field.Checkbox. ...
 
 checkboxfield : Alias for Ext.form.field.Checkbox. ...
 
 checkboxgroup : Alias for Ext.form.CheckboxGroup. ...
 
 checkcolumn : Alias for Ext.grid.column.CheckColumn. ...
 
 colormenu : Alias for Ext.menu.ColorPicker. ...
 
 colorpicker : Alias for Ext.picker.Color. ...
 
 combo : Alias for Ext.form.field.ComboBox. ...
 
 combobox : Alias for Ext.form.field.ComboBox. ...
 
 component : Alias for Ext.Component. ...
 
 container : Alias for Ext.container.Container. ...
 
 cycle : Alias for Ext.button.Cycle. ...
 
 dataview : Alias for Ext.view.View. ...
 
 datecolumn : Alias for Ext.grid.column.Date. ...
 
 datefield : Alias for Ext.form.field.Date.

 datemenu : Alias for Ext.menu.DatePicker. ...
 
 datepicker : Alias for Ext.picker.Date. ...
 
 displayfield : Alias for Ext.form.field.Display. ...
 
 draw : Alias for Ext.draw.Component. ...
 
 editor : Alias for Ext.Editor. ...
 
 eventrecordermanager : Alias for Ext.ux.event.RecorderManager. ...
 
 field : Alias for Ext.form.field.Base. ...
 
 fieldcontainer : Alias for Ext.form.FieldContainer. ...
 
 fieldset : Alias for Ext.form.FieldSet. ...
 
 filebutton : Alias for Ext.form.field.FileButton. ...
 
 filefield : Alias for Ext.form.field.File. ...
 
 fileuploadfield : Alias for Ext.form.field.File. ...
 
 flash : Alias for Ext.flash.Component. ...
 
 form : Alias for Ext.form.Panel. ...
 
 gmappanel : Alias for Ext.ux.GMapPanel. ...
 
 grid : Alias for Ext.grid.Panel. ...
 
 gridcolumn : Alias for Ext.grid.column.Column. ...
 
 gridpanel : Alias for Ext.grid.Panel. ...
 
 gridview : Alias for Ext.grid.View. ...
 
 grouptabpanel : Alias for Ext.ux.GroupTabPanel. ...
 
 header : Alias for Ext.panel.Header. ...
 
 headercontainer : Alias for Ext.grid.header.Container. ...
 
 hidden : Alias for Ext.form.field.Hidden. ...
 
 hiddenfield : Alias for Ext.form.field.Hidden. ...
 
 htmleditor : Alias for Ext.form.field.HtmlEditor. ...
 
 image : Alias for Ext.Img. ...
 
 imagecomponent : Alias for Ext.Img. ...
 
 itemselector : Alias for Ext.ux.form.ItemSelector. ...
 
 itemselectorfield : Alias for Ext.ux.form.ItemSelector. ...
 
 jsonpstore : Alias for Ext.data.JsonPStore. ...
 
 label : Alias for Ext.form.Label. ...
 
 loadmask : Alias for Ext.LoadMask. ...
 
 menu : Alias for Ext.menu.Menu. ...
 
 menucheckitem : Alias for Ext.menu.CheckItem. ...
 
 menuitem : Alias for Ext.menu.Item. ...
 
 menuseparator : Alias for Ext.menu.Separator. ...
 
 messagebox : Alias for Ext.window.MessageBox. ...
 
 multiselect : Alias for Ext.ux.form.MultiSelect. ...
 
multiselectfield : Alias for Ext.ux.form.MultiSelect. ...
 
 multislider : Alias for Ext.slider.Multi. ...
 
 numbercolumn : Alias for Ext.grid.column.Number. ...
 
 numberfield : Alias for Ext.form.field.Number. ...
 
 pagingtoolbar : Alias for Ext.toolbar.Paging. ...
 
 panel : Alias for Ext.panel.Panel. ...
 
 pickerfield : Alias for Ext.form.field.Picker. ...
 
 progressbar : Alias for Ext.ProgressBar. ...
 
 propertygrid : Alias for Ext.grid.property.Grid. ...
 
 quicktip : Alias for Ext.tip.QuickTip. ...
 
 radio : Alias for Ext.form.field.Radio. ...
 
 radiofield : Alias for Ext.form.field.Radio. ...
 
 radiogroup : Alias for Ext.form.RadioGroup. ...
 
 rownumberer : Alias for Ext.grid.column.RowNumberer. ...
 
 slider : Alias for Ext.slider.Single. ...
 
 sliderfield : Alias for Ext.slider.Single. ...
 
 slidertip : Alias for Ext.slider.Tip. ...
 
 spinnerfield : Alias for Ext.form.field.Spinner. ...
 
 splitbutton : Alias for Ext.button.Split. ...
 
 splitter : Alias for Ext.resizer.Splitter. ...
 
 statusbar : Alias for Ext.ux.statusbar.StatusBar. ...
 
 tab : Alias for Ext.tab.Tab. ...
 
 tabbar : Alias for Ext.tab.Bar. ...
 
 tablepanel : Alias for Ext.panel.Table. ...
 
 tableview : Alias for Ext.view.Table. ...
 
 tabpanel : Alias for Ext.tab.Panel. ...
 
 tbfill : Alias for Ext.toolbar.Fill. ...
 
 tbitem : Alias for Ext.toolbar.Item. ...
 
 tbseparator : Alias for Ext.toolbar.Separator. ...
 
 tbspacer : Alias for Ext.toolbar.Spacer. ...
 
 tbtext : Alias for Ext.toolbar.TextItem. ...
 
 templatecolumn : Alias for Ext.grid.column.Template. ...
 
 text : Alias for Ext.draw.Text. ...
 
 textarea : Alias for Ext.form.field.TextArea. ...
 
 textareafield : Alias for Ext.form.field.TextArea. ...
 
 textfield : Alias for Ext.form.field.Text. ...
 
 timefield : Alias for Ext.form.field.Time. ...
 
 timepicker : Alias for Ext.picker.Time. ...
 
 tip : Alias for Ext.tip.Tip. ...
 
 tool : Alias for Ext.panel.Tool. ...
 
 toolbar : Alias for Ext.toolbar.Toolbar. ...
 
 tooltip : Alias for Ext.tip.ToolTip. ...
 
 treepanel : Alias for Ext.tree.Panel. ...
 
 treepicker : Alias for Ext.ux.TreePicker. ...
 
 treeview : Alias for Ext.tree.View. ...
 
 trigger : Alias for Ext.form.field.Trigger. ...
 
 triggerfield : Alias for Ext.form.field.Trigger. ...
 
 uxiframe : Alias for Ext.ux.IFrame. ...
 
 viewport : Alias for Ext.container.Viewport. ...
 
 window : Alias for Ext.window.Window. ...
 -->