/**
 * 
 */
Ext.define('Zero.view.install.AppsForm',{
			extend:'Ext.form.FormPanel',
			alias:'widget.appsform',
			mixins:['Zero.util.ex.StructureFormData'],
			layout:{
				type:'vbox',
				align:'stretch'
			},
});